-- Seed quiz questions with romantic/personal topics

INSERT INTO quiz_questions (id, question, options, correct_option, explanation, difficulty, created_at, updated_at)
VALUES
    (uuid_generate_v4(),
     'İlk randevumuzda nereye gitmiştik?',
     '["Kafe", "Park", "Sinema", "Restoran"]'::jsonb,
     2,
     'İlk randevumuz parkta çok güzeldi!',
     'EASY',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'En sevdiğim renk nedir?',
     '["Mavi", "Pembe", "Yeşil", "Mor"]'::jsonb,
     3,
     'Mor rengi çok severim, bunu biliyordun!',
     'EASY',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'Hangi yemek türünü en çok severim?',
     '["İtalyan", "Japon", "Türk", "Çin"]'::jsonb,
     0,
     'İtalyan mutfağını bayılarak yerim!',
     'EASY',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'İlk defa ne zaman "Seni seviyorum" dedim?',
     '["İlk buluşmamızda", "Bir ay sonra", "Üç ay sonra", "Altı ay sonra"]'::jsonb,
     1,
     'Tam bir ay sonra cesaret edip söylemiştim!',
     'MEDIUM',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'En çok hangi müzik türünü dinlerim?',
     '["Pop", "Rock", "Rap", "Klasik"]'::jsonb,
     0,
     'Pop müzik favorim, hep birlikte söylüyoruz!',
     'EASY',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'Hayalimdeki tatil yeri neresi?',
     '["Paris", "Bali", "Tokyo", "New York"]'::jsonb,
     0,
     'Paris her zaman hayalimdi, birlikte gideceğiz!',
     'MEDIUM',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'En sevdiğim çiçek hangisi?',
     '["Gül", "Papatya", "Lale", "Orkide"]'::jsonb,
     0,
     'Kırmızı güller favorim!',
     'EASY',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'Kahvemi nasıl içerim?',
     '["Sade", "Sütlü", "Şekerli", "Türk kahvesi"]'::jsonb,
     1,
     'Sütlü kahve benim için vazgeçilmez!',
     'EASY',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'En sevdiğim mevsim hangisi?',
     '["İlkbahar", "Yaz", "Sonbahar", "Kış"]'::jsonb,
     2,
     'Sonbahar renklerini ve havasını çok severim.',
     'EASY',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'Hangi film türünü izlemeyi tercih ederim?',
     '["Komedi", "Dram", "Korku", "Romantik"]'::jsonb,
     3,
     'Romantik komedilere bayılırım!',
     'EASY',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'İlk hediyende bana ne almıştın?',
     '["Kitap", "Çiçek", "Parfüm", "Kolye"]'::jsonb,
     3,
     'İlk hediye kolye çok özeldi, hala saklıyorum!',
     'MEDIUM',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'En sevdiğim hayvan hangisi?',
     '["Kedi", "Köpek", "Kuş", "Balık"]'::jsonb,
     0,
     'Kedilere bayılırım!',
     'EASY',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'Hafta sonu en çok ne yapmayı severim?',
     '["Kitap okumak", "Dizi izlemek", "Gezmek", "Uyumak"]'::jsonb,
     2,
     'Seninle gezmeyi her şeyden çok severim!',
     'EASY',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'En sevdiğim dondurma aroması nedir?',
     '["Çikolata", "Çilek", "Vanilya", "Fıstık"]'::jsonb,
     0,
     'Çikolatalı dondurma her zaman favorim!',
     'EASY',
     NOW(),
     NOW()),

    (uuid_generate_v4(),
     'Rüyalarımda en çok ne görürüm?',
     '["Seyahat", "Seni", "İş", "Aile"]'::jsonb,
     1,
     'Rüyalarımda hep sen varsın aşkım!',
     'MEDIUM',
     NOW(),
     NOW());
